DEV-1642: Store and read clients from file
cloudradar-monitoring/rport pull request #28
Opened 2020-08-28 00:42 UTC by m-terel

2020-08-30 09:50 UTC, nikita-vanyasin commented on cmd/rportd/main.go
> +	csrFileName := flag.String("csr-filename", DefaultCSRFileName, "")
Documentation for newly added flags is absent. Please update serverHelp.

2020-08-30 09:54 UTC, nikita-vanyasin commented on constant/const_windows.go
> +const (
Variable value for 'windows' build tag points to non-windows directory (/var/lib/rportd).
Cagent uses ProgramData : https://github.com/cloudradar-monitoring/cagent/blob/master/config.go#L313
I guess rportd should use similar path, though it's better to ask Thorsten.

2020-08-30 09:59 UTC, nikita-vanyasin commented on constant/const.go
> +package constant
I don't really like the idea of having a package with such a common name. I think the constant values should be placed as close to the place where it's used as possible.
Also, it's very probable that in the future we will allow users to change this value via config or CLI argument. (e.g. users can change this value for cagent project).
Therefore it's just a default value for configuration and better to place it near Config type definition.

2020-08-30 10:08 UTC, nikita-vanyasin commented on server/csr/cleanup.go
> +package csr
I'm not sure 'csr' is a good name for this package because some of defined types are not really related to 'session repository'. e.g. Tunnel type actually implements connection proxying which is not related to a tasks related to a storing any values into persistent or cache storage.
It happened because the Client Session and Tunnel types acting not only as data-object (DTO, which is very good for 'repository' package) but as objects implementing some business logic (creating new tunnels, establishing proxy etc.). But I'm not sure separation of this entities now will bring any help for future development. 
Do we really need that new package? maybe it's enough to create a new package that will know how to store/retrieve data from different storages ?

2020-08-30 10:14 UTC, nikita-vanyasin requested changes
Seems good to me except some remarks regarding package naming (see comments).

Also, please fix lint warnings. You can run linter locally using `make docker-golangci-lint` without pushing changes.

2020-08-31 11:45 UTC, m-terel commented on server/csr/cleanup.go
> +package csr
Agree that after moving other files 'csr' is not an accurate naming for it. What about renaming it to "sessions"?

2020-08-31 13:26 UTC, nikita-vanyasin commented on server/csr/cleanup.go
> +package csr
:+1:

2020-09-01 07:29 UTC, nikita-vanyasin requested changes

2020-09-01 07:29 UTC, nikita-vanyasin commented on server/const_windows.go
> +	DirectorySeperator   = "\\"
There is os.PathSeparator for that.

2020-09-01 07:35 UTC, m-terel commented on server/const_windows.go
> +	DirectorySeperator   = "\\"
thanks:) fixed.

2020-09-01 07:51 UTC, nikita-vanyasin approved these changes

2020-09-01 08:23 UTC, merged