Dev 2370 auth app 2fa
cloudradar-monitoring/rport pull request #332
Opened 2021-10-25 21:34 UTC by breathbath

2021-10-27 06:53 UTC, devgek submitted a review, later dismissed

2021-11-04 14:30 UTC, breathbath commented on cmd/rportd/main.go
> +	viperCfg.SetDefault("api.totp_secret", "")
ok

2021-11-05 07:29 UTC, devgek approved these changes

2021-11-08 14:45 UTC, domenipavec requested changes

2021-11-08 14:45 UTC, domenipavec commented on server/bearer_auth.go
> +		al.Errorf(
Not sure all these error logs are the best idea. Especially this one - if someone is trying to brute force the password and get banned, they could really increase the log size by hitting this log point.

2021-11-08 14:45 UTC, domenipavec commented on server/api.go
> +	al.auditLog.Entry("users-totp-secret", auditlog.ActionDelete).
Please add the application to auditlog constants, so we have a central list of all possible values.
Also add saving auditlog entries to other endpoints that modify totp secrets.

2021-11-08 14:45 UTC, domenipavec commented on server/api.go
> +		w.WriteHeader(http.StatusCreated)
It would be nice to return the secret and image to user on create request, so they don't have to make another request.

2021-11-08 14:45 UTC, domenipavec commented on server/totp.go
> +	usr.TotP = string(totPBytes)
Not sure how big the image is, but it's a bit weird we're saving that in db. We could just generate it on the fly when needed.

2021-11-08 14:45 UTC, domenipavec commented on server/api.go
> +	issuer := req.URL.Query().Get("application-name")
Not sure what the use case would be to have the user set the issuer themselves. I think the issuer should just be a constant.

2021-11-08 14:45 UTC, domenipavec commented on server/api.go
> +func (al *APIListener) handleGetTotP(w http.ResponseWriter, req *http.Request) {
I'm not sure if it has any security implications to allow users to read their secret later, but most sites I've seen only show you the code when it's first generated and don't allow reading it again. So I would drop the get endpoint here and only return the code to the user in create endpoint.

2021-11-08 14:45 UTC, domenipavec commented on server/config.go
> +	TotPEnabled             bool            `mapstructure:"totp_enabled"`
Since you're treating this differently from 2FA, you have to check this as well anywhere where `IsTwoFAOn` is checked. For example in `handleBasicAuth`, where it's decided whether username and password should be accepted. Otherwise using basic auth would be possible even when totp is enabled. 
Might be easier to add it to `IsTwoFAOn`?

2021-11-08 14:45 UTC, domenipavec commented on server/api.go
> +		tokenStr, err := al.createAuthToken(lifetime, username, "/api/v1/me/totp-secret")
You definitely shouldn't always give access to `/me/totp-secret` - it would be ok on the first login when user doesn't have the secret so they can generate it. But for later logins, this exposes a huge security hole, since the user can just read the secret and generate the token - basically bypassing totp 2FA protection.

2021-11-08 14:45 UTC, domenipavec commented on server/api.go
> +	if al.config.API.TotPEnabled {
You should verify the jwt token you're returning after login in this endpoint as well to solve the 2nd vulnerability I described in my previous review:
```Requiring no password or server generated token when validating 2fa, means that it's easy to login without knowing the password with only totp token. I simply try every few minutes, eventually the user will try to login, and I will also be able to login as that user with only totp token.```

2021-11-14 06:51 UTC, breathbath commented on rportd.example.conf
> +  # totp_enabled = false
ok

2021-11-14 06:52 UTC, breathbath commented on server/bearer_auth.go
> +		al.Errorf(
ok

2021-11-14 06:59 UTC, breathbath commented on server/api.go
> +	al.auditLog.Entry("users-totp-secret", auditlog.ActionDelete).
ok done

2021-11-14 07:04 UTC, breathbath commented on server/api.go
> +		w.WriteHeader(http.StatusCreated)
ok

2021-11-14 08:06 UTC, breathbath commented on server/totp.go
> +	usr.TotP = string(totPBytes)
hey it was tickets requirement, but the idea is great I changed the implementation to the runtime generation

2021-11-14 08:10 UTC, breathbath commented on server/api.go
> +	issuer := req.URL.Query().Get("application-name")
The use case is that this field is visible in the authenticator app as the application name, maybe someone is unhappy about the "rport" name and wants to use another name e.g. "super-fancy-server-management-tool"

2021-11-14 08:12 UTC, breathbath commented on server/api.go
> +func (al *APIListener) handleGetTotP(w http.ResponseWriter, req *http.Request) {
this was a ticket requirement, but anyway if you can generate and read it at any time it's the same security problem as to just read it. The only security issue here is that we store the secret in database which might be exposed. But as mentioned - this is one of the requirements.

2021-11-14 08:23 UTC, breathbath commented on server/config.go
> +	TotPEnabled             bool            `mapstructure:"totp_enabled"`
I've added this check to the basic auth use case, but I would not add it as part of `IsTwoFAOn` as it might interfere with other use cases where IsTwoFAOn is expected to be true but TotPEnabled is false

2021-11-14 08:25 UTC, breathbath commented on server/api.go
> +		tokenStr, err := al.createAuthToken(lifetime, username, "/api/v1/me/totp-secret")
first it's a ticket requirement, secondly there is no hole because to use this api you should first pass login an generate a special jwt token which cannot be used in other APIs.

2021-11-14 09:02 UTC, breathbath commented on server/api.go
> +	if al.config.API.TotPEnabled {
sorry I would not use the word "easy" here: imagine you have to guess a 6 digit number which is changing every 30s and do it in the time range between eventual login and user's 2fa auth success or login attempt timeout. But actually the same issue is with the existing 2fa, I might try to guess the code which was sent to the user in the time between login and 2fa check. 

Our current implementation  assumes that the user who tried to login is the same who is trying the 2fa code by the fact that user provided a correct code in the expected time range, and there we could also use some intermediate jwt token to relate both actions.

2021-11-16 09:50 UTC, domenipavec commented on server/api.go
> +	issuer := req.URL.Query().Get("application-name")
I guess, don't really care about this that much :)

2021-11-16 10:03 UTC, domenipavec commented on server/api.go
> +		tokenStr, err := al.createAuthToken(lifetime, username, "/api/v1/me/totp-secret")
Ticket requirements clearly state that access to `/me/totp-secret`  should be given with only username and password only if user hasn't generate the secret yet:

> If totp_secret IS NULL we must permit the log in with just username and password and the only Endpoint, the user is allowed to use is /me/totp-secret. This enables and forces the user to create the secrete and activate the app.

Once the user has generated the secret allowing them access to `/me/totp-secret` without the 2FA token bypasses the need for having the ability to generate totp tokens.

For example I find out someone's username and password. I'm able to login with that username and password and access `/me/totp-secret` to generate a new totp secret with which I can then gain full access.

The point of 2FA/totp authentication is that anyone logging in must know both password and the token to gain access.

2021-11-16 10:03 UTC, domenipavec commented on server/api.go
> +	if al.config.API.TotPEnabled {
The point of 2FA/totp authentication is that anyone logging in must know both password and the token to gain access.

If I somehow gain access to the totp secret I'm able to generate totp token I still must not be able to login without the password. Which your implementation enables me: if I just keep trying to login I will eventually be able to login once the user has entered password. This is not about guessing the token but about the case where I know the totp secret.

You should not assume that the user who provided the password is the same as the one providing the token. As you mentioned you should use the intermediate jwt to connect the actions.

2021-11-27 22:49 UTC, breathbath commented on server/api.go
> +	issuer := req.URL.Query().Get("application-name")
???

2021-11-27 22:58 UTC, breathbath commented on server/api.go
> +		tokenStr, err := al.createAuthToken(lifetime, username, "/api/v1/me/totp-secret")
if user looses access to his phone he automatically looses access to his account.  I understand /me/totp-secret as a way to do this and also do the first validation, e.g. with Google 2fa I can manage totp secret keys at any time, but probably after the second check and possibly another password request, but the ticket doesn't mention this case at all.

2021-11-27 23:02 UTC, breathbath commented on server/api.go
> +	if al.config.API.TotPEnabled {
same applies for the current 2fa - a hacker gains access to the users email + 2fa code and applies it without knowing login and password.

2021-11-28 18:44 UTC, breathbath commented on server/api.go
> +func (al *APIListener) handleGetTotP(w http.ResponseWriter, req *http.Request) {
token post api can only be used with the login token for the first time, in all other cases we require a token which is given after the totp check

2021-11-28 18:55 UTC, breathbath commented on server/api.go
> +		tokenStr, err := al.createAuthToken(lifetime, username, "/api/v1/me/totp-secret")
I changed the code as follows:
- if totp is enabled, user gets a special login token after login api (a token with totp scope)
- the login token can used to create a new totp secret (POST to /me/tot-p-secret) only if no other secret was created
- the login token is required in /check-2fa if totp is enabled, if a valid totp code is given, user gets a proper token (with an empty scope)
- the login token cannot be used in all other apis
- the proper token can be used to create, delete and read totp secrets

2021-11-28 18:55 UTC, breathbath commented on server/api.go
> +	if al.config.API.TotPEnabled {
I've solved it see my previous comment

2021-11-29 15:50 UTC, domenipavec approved these changes
A few minor comments, otherwise LGTM.

2021-11-29 15:50 UTC, domenipavec commented on api-doc.yml
> +      If time based one time passwords (TotP) are enabled (Google/Microsoft authenticator app), returns authorization JWT token. However this token can be used only for `/me/totp-secret` URLs.\n
You should update the description.

2021-11-29 15:50 UTC, domenipavec commented on server/2fa_auth.go
> +		expiry: time.Now().Add(loginSessionTTL),
Nit.: I don't think tracking expiry here is necessary anymore, since you generate jwt token with expiry on login anyway.

2021-11-29 15:50 UTC, domenipavec commented on server/2fa_auth_test.go
> +	require.EqualError(t, err, "invalid codem")
Typo?

2021-11-29 15:50 UTC, domenipavec commented on server/api.go
> +func (al *APIListener) handlePostVerify2FAToken() http.Handler {
Why is this method returning a handler instead of being the handler itself? It doesn't seem you're using closure so it would be required?

2021-11-29 15:50 UTC, domenipavec commented on server/bearer_auth.go
> +var ScopesExcluding2FaCheck = []Scope{
I think the name is confusing. Shouldn't it be like `Allow all` scope or something?

2021-12-02 18:08 UTC, merged