DEV-2528 implementation of filters for client-auth
cloudradar-monitoring/rport pull request #555
Opened 2022-05-31 17:47 UTC by thorstenkramm

2022-06-02 17:07 UTC, domenipavec requested changes

2022-06-02 17:07 UTC, domenipavec commented on server/server.go
> +		return clientsauth.NewFileProvider(config.Server.AuthFile), nil
I think that for `FileProvider` we should still use cache, otherwise the whole json file must be loaded on every client connection, which could be potentially expensive.

2022-06-02 17:07 UTC, domenipavec commented on server/api_clientauth_test.go
> +		msg := fmt.Sprintf("test case: %q", tc.descr)
Please use `t.Run` to add `descr` to test name and remove `msg`.

2022-06-02 17:07 UTC, domenipavec commented on server/api_clientauth_test.go
> +	}{
It would be good to add test cases for empty id filter, successful filter with one result.

2022-06-02 17:07 UTC, domenipavec commented on server/clientsauth/clientauth.go
> +var SupportedFields = map[string]map[string]bool{
You can pass `nil` for supported and default fields to remove support for fields on this endpoint, since it makes no sense with only `id`.

2022-06-02 17:07 UTC, domenipavec commented on server/api_clientauth_test.go
> +		msg := fmt.Sprintf("test case: %q", tc.descr)
Same as above.

2022-06-06 09:02 UTC, thorstenkramm commented on server/clientsauth/database.go
> +func NewDatabaseMockProvider(clients []*ClientAuth) *DatabaseProvider {
@domenipavec As far as I know, a function inside a _test file, has a file-only scope. One test cannot use functions declared in another test. Moving the mock function `NewDatabaseMockProvider` into a separated _test file seems not possible. Or am I missing something?

2022-06-07 12:06 UTC, domenipavec commented on server/api_clientauth_test.go
> +			msg := fmt.Sprintf("test case: %q", tc.descr)
Msg is not required anymore since you're using t.Run

2022-06-07 12:20 UTC, domenipavec commented on server/api_clientauth_test.go
> +			msg := fmt.Sprintf("test case: %q", tc.descr)
Same

2022-06-07 12:20 UTC, domenipavec commented on server/clientsauth/file.go
> +		cache:    cache,
You need to either delete or update cache on `Add`

2022-06-07 12:20 UTC, domenipavec commented on share/query/convert.go
> +					operatorCode = "LIKE"
This will do case sensitive comparison, while the non db code will do case insensitive. We should do the same here.

Also I implemented the same thing in my PR, I think my implementation is a bit cleaner: https://github.com/cloudradar-monitoring/rport/pull/562/files#diff-d8c93b1d3989c57232dc1cce22fdb2c250a647f6a708a21bdaf6096291ba74e1R43 
If you agree merge my PR and rebase this on top.

2022-06-09 12:44 UTC, thorstenkramm commented on share/query/convert.go
> +					operatorCode = "LIKE"
@domenipavec I adopted your approach. I appended escaping the `%` so users can't use this sign to trigger a wildcard search.

2022-06-09 14:27 UTC, domenipavec submitted a review, later dismissed

2022-06-10 11:21 UTC, merged