[DEV-2537, 2631, 2632] Use tags for targeting
cloudradar-monitoring/rport pull request #658
Opened 2022-08-02 05:20 UTC by morestatic

Allows command, scripts, scheduled jobs and file upload features to use tags for targeting clients for execution related tasks.

2022-08-03 17:57 UTC, domenipavec requested changes
Reviewing PRs this big is very time consuming. I would appreciate it if you split your code changes into smaller PRs in the future.

I like all the tests you added :+1:

2022-08-03 17:57 UTC, domenipavec commented on server/api_handler_schedules.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &scheduleInput, 2)
Schedules don't have a separate endpoint for single client execution, so we should definitely allow only 1 client here.

2022-08-03 17:57 UTC, domenipavec commented on server/api_handler_schedules.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &scheduleInput, 2)
Same

2022-08-03 17:57 UTC, domenipavec commented on server/api_handler_schedules.go
> +	var orderedClients []*clients.Client
Why is this a separate definition, it would get defined below anyway?

2022-08-03 17:57 UTC, domenipavec commented on server/api_handler_commands.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &reqBody, 2)
Please make `2` a constant with descriptive name.
Same for other places where you use constant numbers.

2022-08-03 17:57 UTC, domenipavec commented on server/api_handler_commands_test.go
> +func TestHandlePostMultiClientCommandWithGroupIDs(t *testing.T) {
I haven't dived deep in these tests, but they look pretty similar. Would it be possible to have them in the same test as separate testcases?

2022-08-03 17:57 UTC, domenipavec commented on server/api/jobs/jobs.go
> +func (p *SqliteProvider) GetDB() (db *sqlx.DB) {
Is this used anywhere?

2022-08-03 17:57 UTC, domenipavec commented on server/api_helper_clients.go
> +	minClients int,
I question having this configurable, especially if it's not actually used in case of `tags` targeting. Maybe we should just change the behavior and always check for minimum of 1 client?

2022-08-03 17:57 UTC, domenipavec commented on server/api_helper_commands.go
> +				if al.insecureForTests {
`insecureForTests` has a very specific function - disabling authentication for tests. I wouldn't use it here. If you require different behavior in tests here you should probably use a different flag or modify the mocks so that it's not needed.

2022-08-03 17:57 UTC, domenipavec commented on server/cgroups/sqlite.go
> +func NewSqliteProvider(db *sqlx.DB) (*SqliteProvider, error) {
Why change this? It makes initialization less self contained and puts even more code in server.go initialization.
I know we do it this way for some other sqlite providers, but that's because we share `sqlx.DB` between multiple providers. Here that's not needed.

2022-08-03 17:57 UTC, domenipavec commented on server/server.go
> +func (m *jobResultChanMap) GetAllKeys() (jobIDs []string) {
Is this used anywhere?
Since the description of the struct is that it is thread safe, this should use the mutex.

2022-08-03 17:57 UTC, domenipavec commented on server/clients/cr.go
> +		availableClients, err = s.GetAll()
I know this error is technically handled, but it makes the code less readable and harder to change. Please use `if err != nil { return nil, err }`

2022-08-03 17:57 UTC, domenipavec commented on server/clients/cr.go
> +	if err == nil && strings.ToUpper(operator) == "AND" {
You can use `strings.EqualFold`

2022-08-03 17:57 UTC, domenipavec commented on server/clients/cr.go
> +					foundCount++
I'm not sure `foundCount` is a good measure as I don't think we validate that there's no duplicate tags. You should just add a boolean found for each tag and check that.

2022-08-03 17:57 UTC, domenipavec commented on server/clients/cr.go
> +func findMatchingORClients(availableClients []*Client, tags []string) (matchingClients []*Client) {
It would be nice to have unit tests for these 2 functions since the logic is non trivial.

2022-08-04 08:19 UTC, morestatic commented
hi @domenipavec, 

thanks for the detailed review. overall, i think nearly all the comments will be accepted. 

yeah, the PR did get too big. agree that the goal should be to keep them smaller and easier to review.

i did talk with @thorstenkramm about refactoring the test code, and we decided to defer for now but it is an outstanding task that needs to be done. i saw your comment about the same test with separate test cases. i think we should take care not to create 'uber' tests that become awkward to deal with. however, there is lots of duplicated test code (and cases) that we need to de-duplicate. i'd prefer to do this via shared functions that are called via more tests rather than making one bigger test. when we decide to do the refactoring happy to discuss the approach though and maybe we can have a call to agree the best way.

noticed your comment about a single client for scheduled jobs. sounds like i don't quite understand how scheduled jobs work. will ask @thorstenkramm to clarify in the related comment. 

ok, thanks again for digging in for the review. will get on with addressing the individual points.

2022-08-04 08:33 UTC, morestatic commented on server/api_handler_schedules.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &scheduleInput, 2)
@thorstenkramm (or maybe @domenipavec) could you clarify the requirement? not sure i understand how the feature works and what we need. the api-docs say client_ids and group_ids are supported, so how and where does the 1 client constraint apply?

2022-08-04 08:36 UTC, morestatic commented on server/api_handler_schedules.go
> +	var orderedClients []*clients.Client
done

2022-08-04 08:40 UTC, morestatic commented on server/api_handler_commands.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &reqBody, 2)
done

2022-08-04 08:55 UTC, morestatic commented on server/api/jobs/jobs.go
> +func (p *SqliteProvider) GetDB() (db *sqlx.DB) {
yep, used in the creation of a `scheduleManager` for test dependency purposes. see below.
https://github.com/cloudradar-monitoring/rport/blob/85cc222f18907e97504727f556c02710e7706dd1/server/api_handler_commands_test.go#L1971
btw, i think how we deal with test dependencies is something we can cover when discussing the test code refactoring. you're much more familar the code base, so might prefer a different approach. mine was somewhat brute force. I'll add a TODO in the code, so that we find to discuss later.

2022-08-04 09:10 UTC, morestatic commented on server/server.go
> +func (m *jobResultChanMap) GetAllKeys() (jobIDs []string) {
yes, again this is something introduced for testing purposes. when testing the WS api, there isn't any available feedback for the test. the multijob id is written by the client listener to directly to the WS, and the client listener isn't instantiated as part of the api listener used for testing. therefore, the test introspects the job results chan keys to find the multijob id, which is then used to find a count of created jobs for checking expectations in the test. i can't say i feel confident about the approach (due to a potential race before the job chan is removed) but it does seem to work (due to the chan interaction sequencing in the test scenario). any thoughts?
https://github.com/cloudradar-monitoring/rport/blob/85cc222f18907e97504727f556c02710e7706dd1/server/api_handler_commands_test.go#L1358

even though only used for testing, agree that it should have the mutex protection. will also add a comment that used for test purposes.

2022-08-04 09:19 UTC, morestatic commented on server/upload.go
> +func validateUploadRequest(ur *UploadRequest) error {
done

2022-08-04 10:34 UTC, morestatic commented on server/clients/cr.go
> +func NewClientRepositoryWithDB(initClients []*Client, keepDisconnectedClients *time.Duration, provider ClientProvider, logger *logger.Logger) *ClientRepository {
again, this was related to creating test dependencies. the `NewClientRepositoryWithDB` function is called in two separate packages (server and server/clients), so can't remain private to one package. however, i'm not sure we're really using the function as initially planned (by me) and was planning to revisit as part of the refactoring. can we come back to this function then? and for now, i'll add a TODO comment?

2022-08-04 10:39 UTC, morestatic commented on server/clients/cr.go
> +		availableClients, err = s.GetAll()
agreed. done.

2022-08-04 10:39 UTC, morestatic commented on server/clients/cr.go
> +	if err == nil && strings.ToUpper(operator) == "AND" {
done

2022-08-04 11:13 UTC, morestatic commented on server/api_helper_commands.go
> +				if al.insecureForTests {
yes, understand. i was just following the pattern previously implemented. 
https://github.com/cloudradar-monitoring/rport/blob/85cc222f18907e97504727f556c02710e7706dd1/server/api_helper_commands.go#L150
agreed about potentially using a new flag or a different mechanism entirely. again, i think we should wait until the test refactor to address? originally, i tried to do something fancy and went down a mocking rabbit hole that was too ambitious for my novice level of understanding of the code base and behavior, so reverted after burning a few hours. will add TODO comments for the flag use.

2022-08-04 11:33 UTC, morestatic commented on server/api/jobs/schedule/manager.go
> +func NewManager(jobRunner JobRunner, db *sqlx.DB, logger *logger.Logger, runRemoteCmdTimeoutSec int) (m *Manager) {
it was related to test dependencies, i wanted to avoid the test spinning up the cron behaviour, which may not have had a valid instantiation for testing purpose and could have crashed. it is a little difficult discovering all the dependency requirements for the tests, so was keen to minimise additional component use.

2022-08-04 11:40 UTC, morestatic commented on server/api/jobs/schedule/manager.go
> -	if len(s.Details.ClientIDs) == 0 && len(s.Details.GroupIDs) == 0 {
i did think about this but decided against it, as the old behaviour would soon be forgotten and the comment would have become stale. ideally the PR could have described how the changes impacted the checks. on a larger project, I think the PR notes could have been important.

2022-08-04 11:41 UTC, morestatic commented on server/api_handler_schedules.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &scheduleInput, 2)
done

2022-08-04 11:44 UTC, morestatic commented on server/api_helper_clients.go
> +	minClients int,
i was a little puzzled why only 1 client was an error? do you know/remember why? it seemed fair that particularly a group might only have a single member at times and that would be valid when targeting group?

2022-08-04 16:43 UTC, domenipavec commented on server/api_handler_schedules.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &scheduleInput, 2)
@morestatic Maybe my comment was unclear. I meant that the argument for min number of clients should be `1`, so that 1 or more clients are allowed, not only 2 or more.

2022-08-04 16:45 UTC, domenipavec commented on server/api_helper_clients.go
> +	minClients int,
I was not the one implementing the feature so I'm not sure. But I think it was meant to encourage users to use single client command execution when there's only 1 client.
I think if @thorstenkramm agrees we can remove the error when there's only 1 client.

2022-08-05 02:02 UTC, morestatic commented on server/clients/cr.go
> +					foundCount++
done

2022-08-05 02:02 UTC, morestatic commented on server/clients/cr.go
> +func findMatchingORClients(availableClients []*Client, tags []string) (matchingClients []*Client) {
done

2022-08-05 05:27 UTC, morestatic commented on server/cgroups/sqlite.go
> +func NewSqliteProvider(db *sqlx.DB) (*SqliteProvider, error) {
again, this was another test dependency mod. we aren't only concerned with the server initialisation but also need to support test setup / dependencies. the usual pattern seems to be to provide a slightly higher level version of the function (for the server initialisation) that then calls the slightly lower level version (which can then also be used for test setup/dependencies). Whether internal or external depends on where the tests are.

2022-08-05 05:33 UTC, morestatic commented on server/api_helper_clients.go
> +	minClients int,
i think consensus is forming that we only need a check for at least 1 client and that the 2 clients check probably isn't required anymore. but i'll confirm with @thorstenkramm.

2022-08-05 05:38 UTC, morestatic commented on server/api_handler_commands_test.go
> +func TestHandlePostMultiClientCommandWithGroupIDs(t *testing.T) {
As mentioned previously, we need to refactor the tests. There are multiple opportunities for them to be improved. In principle, I'd like to stick with tests per api, but it does get interesting when a number of the apis shared the same validation. now we have the shared validation fn, we should probably have unit tests for that individual fn and then less in the api tests. we can do this when we do the test refactoring.

2022-08-05 07:28 UTC, morestatic commented on server/api_handler_schedules.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &scheduleInput, 2)
done

2022-08-05 07:30 UTC, morestatic commented on server/api_helper_clients.go
> +	GetTags() (tags []string)
done

2022-08-05 09:31 UTC, morestatic commented on server/clients/test_helpers.go
> +func NewFakeClientProvider(t *testing.T, exp *time.Duration, cs ...*Client) *SqliteProvider {
This is another function used for test setup.

2022-08-05 09:33 UTC, morestatic commented on server/api_handler_schedules.go
> +	orderedClients, _, isBadRequest, errTitle, err := al.getOrderedClientsWithValidation(ctx, &scheduleInput, 2)
@domenipavec ok. yes, we're gonna move to checking for a single client only. that's done now.

2022-08-05 09:34 UTC, morestatic commented on server/api_helper_clients.go
> +func (al *APIListener) makeJSONErr(w http.ResponseWriter, err error, errTitle string, isBadRequest bool) {
ok. yes, tried to tidy up the error handling and move everything to APIErrors. we might need one more iteration to finalise but not too far away now. please check the latest commits.

2022-08-08 10:08 UTC, domenipavec commented on server/api_helper_clients.go
> +	if orderedClients == nil || len(orderedClients) < minClientsForTargeting {
`len` of nil slice is 0, so you don't have to make 2 separate checks.

2022-08-08 10:08 UTC, domenipavec commented on server/api_responses.go
> +func (al *APIListener) jsonErrorResponseWithAPIError(w http.ResponseWriter, err error) {
We already have `jsonError` method that should correctly handle `APIError`, please don't add additional method.

2022-08-08 10:14 UTC, domenipavec commented on server/clients/cr.go
> +		}
Here's how I would simplify this code:
```
foundAllTags := true
for _, tag := range tags {
  foundTag := false
  for _, clTag := range clientTags {
    if tag == clTag {
      foundTag = true
      break
    }
  }
  if !foundTag {
    foundAllTags = false
    break
  }
}
if foundAllTags {
  matchingClients = append(matchingClients, cl)
}
```
No need for maps and counts.

2022-08-08 13:49 UTC, morestatic commented on server/api/jobs/model.go
> +func MakeClientTagsAsString(jobTags *models.JobClientTags) (clientTags string) {
i did think about it but what happens when the jobClientTags are nil? when I tried I got `<nil>` in the output. did I miss something, that could allow for rendering a nicer nil value?

2022-08-08 13:52 UTC, morestatic commented on server/api_helper_clients.go
> +	if orderedClients == nil || len(orderedClients) < minClientsForTargeting {
old habits die hard :)

done.

2022-08-08 13:53 UTC, morestatic commented on server/clients/cr.go
> +		}
ok. yes, this is better. thanks.

done.

2022-08-08 14:05 UTC, morestatic commented on server/api_responses.go
> +func (al *APIListener) jsonErrorResponseWithAPIError(w http.ResponseWriter, err error) {
done.

2022-08-08 15:48 UTC, morestatic commented on server/api/jobs/model.go
> +func MakeClientTagsAsString(jobTags *models.JobClientTags) (clientTags string) {
Haven't actually used nil receivers before, so thought i'd try. Yes, works fine. So moved this helper function to a stringer, as suggested. It feels better.

2022-08-09 17:59 UTC, domenipavec approved these changes

2022-08-10 09:56 UTC, merged