Feature/dev 2684 password invalidation
cloudradar-monitoring/rport pull request #790
Opened 2022-11-15 10:16 UTC by edoardoc

https://tracker.rport.io/issue/DEV-2684

2022-11-15 15:42 UTC, domenipavec requested changes
The ticket mentions implementations for both db and json user stores. Are you going to do the json implementation in separate PR?

2022-11-15 15:42 UTC, domenipavec commented on server/api_listener.go
> +	if user.PasswordExpired {
This function also handles token authentication as well as password. I think in case the token is used, this check should not happen.

2022-11-15 15:42 UTC, domenipavec commented on server/api/users/user.go
> +	ActionPasswordExpired string   `json:"password_expired" db:"-"`
Why is this a separate field? And why is it a string?

2022-11-15 15:42 UTC, domenipavec commented on server/api_handler_login.go
> +	// is it expired?
This comment is basically the same as code.

2022-11-15 15:42 UTC, domenipavec commented on server/api_handler_login.go
> +	// you can let through only the newPassword field from here (not from GET)
I'm not sure I understand this comment.

2022-11-15 15:42 UTC, domenipavec commented on server/api_handler_login.go
> +	// a new password is provided?
Change this to single line comment. I would also make it a sentence, like:
`Only set the new password after the old password has been verified.`

2022-11-16 06:55 UTC, edoardoc commented on server/api/users/database.go
> +	if usr.Username == "" && usr.Password != "" { // I am updating the password
cause its a specific case, where password_expired goes to false at the same time as a new passwors gets in.

(similar to the case below where the username gets updated)

2022-11-16 06:59 UTC, edoardoc commented on server/api/users/database.go
> +	s := "username, password, password_expired"
no, I could not see the compatibility-with-old-db-versions in the task, indeed this would not work in that case.
For your second statement, checkDatabaseTables checks all the columns via getSelectClause and by calling it in a select; so it will throw an error when not present.

2022-11-16 07:06 UTC, edoardoc commented on server/api_listener.go
> +	if user.PasswordExpired {
per @thorstenkramm instructions I was told "The user must be kicked out immediately" and for the token I am to await another job to finish so to invalidate the token also (possibly in the same context, I am not sure)

2022-11-16 07:13 UTC, edoardoc commented on server/api/users/user.go
> +	ActionPasswordExpired string   `json:"password_expired" db:"-"`
Since the field itself is a boolean, but no update can be decided upon a boolean only field (cause you have no "presence" check),
I decided to add an API only string field ActionPasswordExpired instead of some added logic, but if you have an easier way we can try and implement that.

2022-11-16 07:14 UTC, edoardoc commented on server/api_handler_login.go
> +	// is it expired?
leftover, removed

2022-11-16 07:15 UTC, edoardoc commented on server/api_handler_login.go
> +	// a new password is provided?
done

2022-11-16 17:21 UTC, edoardoc commented on server/api_handler_login.go
> +	// you can let through only the newPassword field from here (not from GET)
ok, will try and make it more understandable

2022-11-17 18:09 UTC, domenipavec commented on server/api_listener.go
> +	if user.PasswordExpired {
I understand the user session must be stopped. But user tokens are not the same as jwt tokens. Jwt tokens are used for user sessions after the initial password login. But user tokens are long lived tokens that are meant to be used in scripts.
I don't think those should stop working on password invalidate. But if that's @thorstenkramm 's requirement, that'sFine with me.

2022-11-17 18:12 UTC, domenipavec commented on server/api/users/database.go
> +	if usr.Username == "" && usr.Password != "" { // I am updating the password
I'm not sure it needs to be a specific case, what's stopping it from being updated simultaneously?

2022-11-17 18:14 UTC, domenipavec commented on server/api/users/user.go
> +func PasswordExpired(f bool) *bool {
We have `ptr.Bool` in `share` that could be used.

2022-11-17 18:15 UTC, domenipavec commented on server/api/users/database.go
> +	s := "username, password, password_expired"
Ok, as long as we note that everyone will need to do a database migration when upgrading to the new version.

2022-11-17 18:15 UTC, domenipavec approved these changes

2022-11-21 08:10 UTC, edoardoc commented on server/api/users/database.go
> +	if usr.Username == "" && usr.Password != "" { // I am updating the password
yes, this block is useless, I have removed it. Thanks

2022-11-21 08:18 UTC, edoardoc commented on server/api/users/user.go
> +func PasswordExpired(f bool) *bool {
I checked the rest of the repo, it is seldom used.

2022-11-21 08:19 UTC, edoardoc commented
> The ticket mentions implementations for both db and json user stores. Are you going to do the json implementation in separate PR?

I have done that also

2022-11-21 09:50 UTC, domenipavec approved these changes

2022-11-21 09:59 UTC, edoardoc commented on server/api/users/database.go
> +	s := "username, password, password_expired"
I have added notes in the db creation docs

2022-11-24 07:53 UTC, domenipavec approved these changes

2022-11-24 12:55 UTC, merged