[DEV-2709] Improve logging
cloudradar-monitoring/rport pull request #808
Opened 2022-11-24 10:00 UTC by morestatic

This PR improves aspects of our general logging approach. We have a customer who's having problems with disconnected clients and connected tunnels being out of sync. It is proving difficult to diagnose as our logs are missing certain information about client disconnects / connects. This PR adds some of the missing info.

The PR also contains a change that isn't specifically related to improved logging that might assist with the customer problem where we will attempt to start tunnels even if the client is marked as disconnected. Ideally this would be a separate PR but in the interests of deploying a change quickly, it has been included with PR.

Also, there is a change, that will be enhanced further after the next pre-release, to log api error responses on the server side. We currently have a number of internal server error responses that aren't logged on the server. A future change will move these logs out from the server log into a separate (and configurable) api responses log.

2022-11-25 12:12 UTC, domenipavec requested changes

2022-11-25 12:12 UTC, domenipavec commented on server/api_handler_clients.go
> +		// try creating tunnels anyway by continuing with the non-active client.
This seems like a bad idea and will probably lead to even more out of sync clients and tunnels if we allow to create active tunnels that don't have a backing connected client.

2022-11-25 12:12 UTC, domenipavec commented on server/api_responses.go
> +	errLog = logger.NewLogger("api-error-response", logger.LogOutput{File: os.Stdout}, logger.LogLevelDebug)
Is there a reason to use a global variable here? I think it should be part of APIListener.

2022-11-25 12:12 UTC, domenipavec commented on server/client_service.go
> +	// if we created the tunnels with a disconnected client then force reconnect the client
This will not actually reconnect the client, it will just make it appear to be connected. This comment is misleading. Also the state of the client connection should be easily determined - either we have an active connection or we don't. Forcing the state without an active connection seems useless to me.

2022-11-25 12:59 UTC, thorstenkramm commented on server/api_handler_clients.go
> +		// try creating tunnels anyway by continuing with the non-active client.
@morestatic @domenipavec 
The intention of this change is to determine if the client status stored in memory is correct.
We want this just for testing purposes. Will be reset to the previous implementation on the next release. 
We have user feedback about clients whose status changed to disconnected while a tunnel (SSH connection) was active and usable. This suggests the assumption that the client was not disconnected, just the information stored on the server, was false. We want to test what happens if we create a tunnel to a client that is shown disconnected on the server but connected on the client.

2022-11-28 05:59 UTC, morestatic commented on server/api_responses.go
> +	errLog = logger.NewLogger("api-error-response", logger.LogOutput{File: os.Stdout}, logger.LogLevelDebug)
moved API Listener. done.

2022-11-28 06:01 UTC, morestatic commented on server/client_service.go
> +	// if we created the tunnels with a disconnected client then force reconnect the client
removed this. done.

2022-11-28 07:37 UTC, thorstenkramm approved these changes

2022-11-28 07:54 UTC, merged