Feature/dev 2683 mass deployment
cloudradar-monitoring/rport pull request #873
Opened 2023-01-09 11:40 UTC by edoardoc

as of
https://tracker.rport.io/issue/DEV-2683/Mass-deployment-by-expirable-tokens
without 
https://tracker.rport.io/issue/DEV-2746/compatibility-with-new-API-tokens

2023-01-09 17:44 UTC, domenipavec requested changes

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_plus_test.go
> +		// Token:    ptr.String("$2y$05$/D7g/d0sDkNSOh.e6Jzc9OWClcpZ1ieE8Dx.WUaWgayd3Ab0rRdxu"),
Not sure why this is commented out. Either remove it or fix the test to accept it.

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_me.go
> +		if r.Scope == "clients-auth" && !user.IsAdmin() {
Why is `clients-auth` treated differently? Permissions will be checked when using the token anyway. And `read+write` token has a broader permission then `clients-auth`.

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_me.go
> +			WithID(r.Prefix).
Can't have 2 id fields in auditlog.

2023-01-09 17:44 UTC, domenipavec commented on server/api/authorization/model.go
> +	ExpiresAt *time.Time `json:"expires_at,omitempty" db:"expires_at"`
ExpiresAt is not used during token validation?

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_me.go
> +			ExpiresAt *time.Time `json:"expires_at"`
Why do we allow setting expires at with update but not during create?

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_me.go
> +			Scope string `json:"scope"`
Why don't we allow changing scope with update? I think create and update should have the same fields.

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_me.go
> +			Prefix    string     `json:"prefix"`
Why allow changing prefix?
I don't think we should allow changing prefix. Especially not without some validation to disallow empty or same prefixes.

2023-01-09 17:44 UTC, domenipavec commented on server/api/authorization/model.go
> +	if i != 8 {
Prefix len should be a constant

2023-01-09 17:44 UTC, domenipavec commented on server/api/authorization/model.go
> +const DefaultTimeoutSec = 60
What's this used for?

2023-01-09 17:44 UTC, domenipavec commented on server/api/authorization/model.go
> +	prefix := prefixedpwd[0:i]
I think it would be nicer to use `strings.SplitN` instead of index and then manually splitting.

2023-01-09 17:44 UTC, domenipavec commented on server/api/authorization/sqlite.go
> +	converter *query.SQLConverter
Are you using converter anywhere?

2023-01-09 17:44 UTC, domenipavec commented on server/api/authorization/sqlite.go
> +		"INSERT INTO"+
You could use ` for multiline query. You don't need to quote fields if they're simple.

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_login_test.go
> +	apiTokenDb, err := sqlite.New(":memory:", api_token.AssetNames(), api_token.Asset, DataSourceOptions)
I think most of this code is duplicated. You could have a helper function that initializes database and creates the token.

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_commands_test.go
> -func TestHandlePostMultiClientWSCommandWithTags(t *testing.T) {
Why delete unrelated test?

2023-01-09 17:44 UTC, domenipavec commented on server/api_handler_commands_test.go
> -func TestHandlePostMultiClientWSScriptWithTags(t *testing.T) {
Same

2023-01-09 18:36 UTC, edoardoc commented on share/random/random.go
> +var ALPHANUM8 = func() string {
I agree, its to support its redefinition during testing;
I didnt know how to redefine alphaNum

2023-01-09 18:38 UTC, edoardoc commented on server/api_handler_plus_test.go
> +		// Token:    ptr.String("$2y$05$/D7g/d0sDkNSOh.e6Jzc9OWClcpZ1ieE8Dx.WUaWgayd3Ab0rRdxu"),
forgot; done

2023-01-09 18:46 UTC, edoardoc commented on server/api_listener.go
> +				if httpverb == "GET" {
so this translates into:

if I want to handleBasicAuth with a valid token
AND
the token I provide is a "read" token
THEN
I am allowed only to access GET verb operations

2023-01-09 18:47 UTC, edoardoc commented on server/api_handler_me.go
> +	al.handleManageCurUserAPIToken(w, req, "list")
could you point me to a place in the repo where I can find a pattern for that?

2023-01-09 18:49 UTC, edoardoc commented on server/api_handler_login_test.go
> +	apiTokenDb, err := sqlite.New(":memory:", api_token.AssetNames(), api_token.Asset, DataSourceOptions)
indeed it is, I was going to ask you about how to handle this, ok will do;

2023-01-10 13:51 UTC, edoardoc commented on server/api_handler_plus_test.go
> +		// Token:    ptr.String("$2y$05$/D7g/d0sDkNSOh.e6Jzc9OWClcpZ1ieE8Dx.WUaWgayd3Ab0rRdxu"),
done

2023-01-10 14:04 UTC, edoardoc commented on server/api/authorization/model.go
> +const DefaultTimeoutSec = 60
leftover, removed

2023-01-10 14:07 UTC, edoardoc commented on server/api_handler_me.go
> +			Prefix    string     `json:"prefix"`
prefix + username is the primary key, so it will never be updated: the only updateable field is ExpiresAt

2023-01-10 14:13 UTC, edoardoc commented on server/api_handler_me.go
> +			WithID(r.Prefix).
oups, 
I changed all of them in a more uniform format `WithID(fmt.Sprintf("[%s,%s]", user.Username, r.Prefix)).`

2023-01-10 15:32 UTC, edoardoc commented on server/api_handler_me.go
> +			ExpiresAt *time.Time `json:"expires_at"`
that is now allowed, also added some testing.

2023-01-10 15:46 UTC, edoardoc commented on server/api/users/user.go
> -	Token           *string  `json:"token,omitempty" db:"token"`
yes, they will have to create new ones after upgrading

2023-01-10 15:51 UTC, edoardoc commented on server/api_handler_me.go
> +	if action == "delete" {
well maybe, but there is handleManageCurUserAPIToken that deals with the getUserModel;

2023-01-11 08:43 UTC, edoardoc commented on server/api_handler_me.go
> +	al.handleManageCurUserAPIToken(w, req, "list")
done, I made enums

2023-01-11 08:43 UTC, edoardoc commented on server/api_handler_me.go
> +		if r.Scope == "clients-auth" && !user.IsAdmin() {
done

2023-01-11 09:59 UTC, domenipavec commented on share/random/random.go
> +var ALPHANUM8 = func() string {
@edoardoc You will need to change `AlphaNum` to variable definition if you want to override it. Define it with `var AlphaNum = func` instead of `func AlphaNum`.

2023-01-11 10:25 UTC, domenipavec commented on server/api_handler_login_test.go
> +	_ = dbProv.Save(ctx, &itemToSave)
You should check the error. You can pass testing.T as argument and use require.NoError here.

2023-01-11 10:25 UTC, domenipavec commented on server/api_handler_me.go
> +			WithID(fmt.Sprintf("[%s,%s]", user.Username, r.Prefix)).
I'm not sure this is great since this field could be used for filtering. I would just put `Username` here and pass prefix using `WithRequest(map[string]any{ "prefix": r.Prefix })`

2023-01-11 10:25 UTC, domenipavec commented on server/api_handler_me.go
> +			WithID(fmt.Sprintf("[%s,%s]", user.Username, newPrefix)).
Same.
Also pass all user input using `WithRequest`

2023-01-11 10:25 UTC, domenipavec commented on server/api_handler_me.go
> +			WithID(fmt.Sprintf("[%s,%s]", user.Username, r.Prefix)).
Same

2023-01-11 10:25 UTC, domenipavec commented on share/enums/scope.go
> +package enums
`enums` package seems too generic for this. Why not just put it in `api` package?

2023-01-11 10:25 UTC, domenipavec commented on server/api_handler_me.go
> +	if action == "delete" {
@edoardoc `handleManageCurUserAPIToken` has 9 lines, meanwhile this is a giant 150 line function. I would much prefer you put the code in each handler directly and duplicate those 9 lines.
Your way makes the code much harder to read. It also breaks all jump to definition navigation, since that throws you to the top of this giant function and then you need to figure out what action is.

2023-01-11 10:25 UTC, domenipavec commented on server/api_handler_me.go
> +			Prefix    string     `json:"prefix"`
@edoardoc Your code is confusing, since you're reading prefix from the body it seems as if it's possible to update it.
Please make this the same as all other endpoints. Prefix is like id, so it should be part of the url for update (url should be '/me/token/{prefix}`).

2023-01-11 10:25 UTC, domenipavec commented on server/api_handler_commands_test.go
> -func TestHandlePostMultiClientWSCommandWithTags(t *testing.T) {
DEV-2746 is for another repository (rportcli). Please address this in this PR, you can't just delete tests.

2023-01-11 10:33 UTC, domenipavec commented on server/api_listener.go
> +				if httpverb == "GET" {
@edoardoc Yes, but the problem is, that we have websocket (/ws) endpoints, that start as GET requests for authorization, but allow executing commands and scripts.

2023-01-11 12:38 UTC, edoardoc commented on server/api_handler_commands_test.go
> -func TestHandlePostMultiClientWSCommandWithTags(t *testing.T) {
ok, sorry for this

2023-01-11 13:07 UTC, edoardoc commented on server/api_handler_me.go
> +	if action == "delete" {
I was merely copying the same pattern used in other parts of this repo: anyway, done

2023-01-11 13:10 UTC, edoardoc commented on server/api/authorization/model.go
> +	if i != 8 {
done

2023-01-11 13:16 UTC, edoardoc commented on share/enums/scope.go
> +package enums
moved it into authorization, afterall is its own package

2023-01-11 13:47 UTC, edoardoc commented on server/api_handler_me.go
> +		if r.Scope == "clients-auth" && !user.IsAdmin() {
asked @thorstenkramm 

> read+write is not broader than client auth because read/write refers to the http verb and not to the resource.
read+write means you can read and write to any resource the user is allowed to access. Read+write as API token scope is not superseeding the resource permissions on user level.

2023-01-11 13:48 UTC, edoardoc commented on server/api_listener.go
> +				if httpverb == "GET" {
asked @thorstenkramm 

> There is a difference between API tokens and JWT. 
You can either go to /login fetch a JWT and then use this JWT for further requests.
Or you can query any API endpoint directly without going to the /login first by using an API Token.

2023-01-11 16:39 UTC, edoardoc commented on server/api_handler_me.go
> +			Prefix    string     `json:"prefix"`
Verb is a PUT, so if I PUT a value (through the request body or not), which is part of the id, I inherently establish a change of the item that I am addressing: your view on the matter is syntactical only, but REST is semantics also; The approach with `/me/token/{prefix}` is certainly better 
...on it

2023-01-11 16:39 UTC, edoardoc commented on server/api_handler_commands_test.go
> -func TestHandlePostMultiClientWSCommandWithTags(t *testing.T) {
done

2023-01-12 07:49 UTC, edoardoc commented on server/api_handler_commands_test.go
> -func TestHandlePostMultiClientWSScriptWithTags(t *testing.T) {
tests are back and fixed with new APITokens

2023-01-12 07:51 UTC, edoardoc commented on server/api/authorization/model.go
> +	ExpiresAt *time.Time `json:"expires_at,omitempty" db:"expires_at"`
now it is

2023-01-12 08:26 UTC, edoardoc commented on server/api_handler_me.go
> +		tokenHashStr := strings.Replace(string(tokenHash), users.HtpasswdBcryptAltPrefix, users.HtpasswdBcryptPrefix, 1)
refactored into users.GenerateTokenHash

2023-01-13 14:21 UTC, domenipavec commented on server/api_handler_me.go
> +	if len(prefix) != 8 {
Use the constant

2023-01-13 14:21 UTC, domenipavec commented on server/api_handler_login_test.go
> +	_ = dbProv.Save(ctx, &itemToSave)
@edoardoc You're saving 2 tokens, but only assigning and checking 1 error. Please check both errors.

2023-01-13 14:21 UTC, domenipavec commented on server/api_listener.go
> +				if httpverb == "GET" {
@edoardoc `read` token implies that user can only read data with this token. It should not allow executing scripts and commands through websocket endpoints.

2023-01-13 14:21 UTC, domenipavec reviewed
I unresolved a few comments above. Please also address those.

2023-01-16 09:22 UTC, edoardoc commented on server/api_listener.go
> +				if httpverb == "GET" {
done

2023-01-16 09:25 UTC, edoardoc commented on server/api/authorization/sqlite.go
> +	converter *query.SQLConverter
nope, leftover, removed

2023-01-16 09:31 UTC, edoardoc commented on server/api_handler_login_test.go
> +	_ = dbProv.Save(ctx, &itemToSave)
CommonAPITokenTestDb creates always two tokens in the db, 

first one with the provided params,
second one with the provided params replacing prefix with "expired1" and ExpiresAt = 2001;
most of the tests they check only for the first one, 

https://github.com/cloudradar-monitoring/rport/blob/69e562c7a51325ab4fce619c63a21958ec6b1469/server/api_handler_login_test.go#L376

checks for the second one.

2023-01-16 09:33 UTC, edoardoc commented on server/api_handler_me.go
> +	if len(prefix) != 8 {
done

2023-01-16 09:35 UTC, edoardoc commented
> I unresolved a few comments above. Please also address those.

I did what I could trying to understand which ones are still standing.
please add a simple "this" comment to the ones you believe they still need addressing

2023-01-16 16:41 UTC, domenipavec commented on server/api/authorization/model.go
> +	prefix := prefixedpwd[0:i]
@edoardoc This (but I guess if you feel strongly your way is better I'm also ok keeping it as is).

2023-01-16 16:45 UTC, domenipavec commented on server/api_handler_login_test.go
> +	require.NoError(t, err)
```suggestion
	itemToSave := authorization.APIToken{
		Username:  username,
		Prefix:    prefix,
		CreatedAt: ptr.Time(time.Date(2001, 1, 1, 1, 0, 0, 0, time.UTC)),
		ExpiresAt: ptr.Time(time.Date(2051, 1, 1, 2, 0, 0, 0, time.UTC)),
		Scope:     scope,
		Token:     token,
	}
	err = dbProv.Save(ctx, &itemToSave)
	require.NoError(t, err)

	itemToSave = authorization.APIToken{
		Username:  username,
		Prefix:    "expired1",
		CreatedAt: ptr.Time(time.Date(2001, 1, 1, 1, 0, 0, 0, time.UTC)),
		ExpiresAt: ptr.Time(time.Date(2001, 1, 1, 2, 0, 0, 0, time.UTC)),
		Scope:     scope,
		Token:     token,
	}
	err = dbProv.Save(ctx, &itemToSave)
	require.NoError(t, err)

```

2023-01-16 20:48 UTC, edoardoc commented on server/api/authorization/model.go
> +	prefix := prefixedpwd[0:i]
honestly cant see which one is better :)
but here you are...

2023-01-17 08:25 UTC, domenipavec approved these changes

2023-01-17 08:25 UTC, domenipavec commented on server/api/authorization/model.go
> +	token := parts[1]
```suggestion
	parts := strings.SplitN(prefixedpwd, "_", 2)
	if len(parts) < 2 {
		return "", "", errors.New("token should be in the format 'prefix_token'")
	}
	prefix := parts[0]
	token := parts[1]
	if len(prefix) != APITokenPrefixLength {
		return "", "", errors.New("invalid token")
	}
```

2023-01-17 09:26 UTC, merged