Issue/dev 2730/signed windows msi package goversioninfo
cloudradar-monitoring/rport pull request #910
Opened 2023-02-14 16:40 UTC by edoardoc

https://tracker.rport.io/issue/DEV-2730/Signed-windows-msi-package

2023-02-14 16:52 UTC, edoardoc commented on .github/workflows/installer_win.yml
> +        run: export VER="1.2.7" && jq '.StringFileInfo.FileVersion = "'"$VER"'" | .StringFileInfo.ProductVersion = "'"$VER"'"' cmd/rport/versioninfo.json > new.json
@thorstenkramm here I need to get the {{.Version}} value, but I could not see it to be assigned anywhere in the build line
please advise

2023-02-15 08:40 UTC, thorstenkramm commented on .github/workflows/installer_win.yml
> +        run: export VER="1.2.7" && jq '.StringFileInfo.FileVersion = "'"$VER"'" | .StringFileInfo.ProductVersion = "'"$VER"'"' cmd/rport/versioninfo.json > new.json
@edoardoc the version is always in the environment variable `${GITHUB_REF_NAME}` set by GitHub

2023-02-15 09:14 UTC, thorstenkramm requested changes

2023-02-15 09:14 UTC, thorstenkramm commented on cmd/rport/resource/LicenseAgreementDlg_HK.wxs
> +            <!-- To enable EULA localization we change it to this: -->
The Eula rtf doc must contain
`Copyright (c) 2022 RealVNC Ltd.` and not `Copyright (c) 2020 CloudRadar`

2023-02-15 09:14 UTC, thorstenkramm commented on cmd/rport/resource/Product.wxs
> +		<WixVariable Id="WixUIBannerBmp" Value="cmd\rport\resource\images\BannerTop.bmp" />
BannerTop.bmp is outdated. Please use our new Logo.

2023-02-15 09:14 UTC, thorstenkramm commented on cmd/rport/resource/Product.wxs
> +		<Icon Id="Icon.exe" SourceFile="cmd\rport\resource\images\app.ico" />
Let's just use the Rport Tunnel Icon here.

2023-02-15 09:14 UTC, thorstenkramm commented on cmd/rport/resource/Product_en-us.wxl
> +   <String Id="ProductDescription">Monitoring agent</String>
RPort is not a monitoring agent
Use "Remote Access and Remote Management Client"

2023-02-15 09:14 UTC, thorstenkramm commented on cmd/rport/resource/Product_en-us.wxl
> +   <String Id="ServiceDescription">Monitors the system's performance, applications and user experience.</String>
Copy and paste leftover.
Use "Connects the system to an RPort server for remote access and remote management".

2023-02-15 10:58 UTC, edoardoc commented on .github/scripts/inunin-stall.ps1
> +echo "Installing and Uninstalling rport..."
done

2023-02-15 10:59 UTC, edoardoc commented on .github/scripts/makemsi.ps1
> +curl --upload-file ./rport-client.msi https://transfer.sh/rport-client.msi
done

2023-02-15 11:01 UTC, edoardoc commented on .github/workflows/installer_win.yml
> +      - name: Use jq to version the client through cmd/rport/versioninfo.json
done

2023-02-15 11:01 UTC, edoardoc commented on .github/workflows/installer_win.yml
> +        run: export VER="1.2.7" && jq '.StringFileInfo.FileVersion = "'"$VER"'" | .StringFileInfo.ProductVersion = "'"$VER"'"' cmd/rport/versioninfo.json > new.json
done

2023-02-15 11:44 UTC, edoardoc commented on cmd/rport/resource/LicenseAgreementDlg_HK.wxs
> +            <!-- To enable EULA localization we change it to this: -->
done

2023-02-15 11:56 UTC, edoardoc commented on cmd/rport/resource/Product.wxs
> +		<WixVariable Id="WixUIBannerBmp" Value="cmd\rport\resource\images\BannerTop.bmp" />
done

2023-02-15 11:56 UTC, edoardoc commented on cmd/rport/resource/Product.wxs
> +		<Icon Id="Icon.exe" SourceFile="cmd\rport\resource\images\app.ico" />
<img width="224" alt="image" src="https://user-images.githubusercontent.com/368717/219021059-2ede0e27-6c67-403e-b0f0-851b668f0dcd.png">
this is what I used

2023-02-15 11:57 UTC, edoardoc commented on cmd/rport/resource/Product_en-us.wxl
> +   <String Id="ProductDescription">Monitoring agent</String>
done

2023-02-15 11:57 UTC, edoardoc commented on cmd/rport/resource/Product_en-us.wxl
> +   <String Id="ServiceDescription">Monitors the system's performance, applications and user experience.</String>
done

2023-02-15 12:00 UTC, edoardoc commented on .github/workflows/installer_win.yml
> +        run: export VER="1.2.7" && jq '.StringFileInfo.FileVersion = "'"$VER"'" | .StringFileInfo.ProductVersion = "'"$VER"'"' cmd/rport/versioninfo.json > new.json
@thorstenkramm GITHUB_REF_NAME = "issue/dev-2730/signed-windows-msi-package-goversioninfo"

(name of the branch)
The installer is expecting to find a x.y.z format;
a string only version would work only as a FileVersion, not a ProductVersion

2023-02-16 06:14 UTC, edoardoc commented on cmd/rport/versioninfo.json
> +    "LegalCopyright": "Copyright (c) 2022 RPort",
done

2023-02-17 10:51 UTC, thorstenkramm requested changes

2023-02-17 10:51 UTC, thorstenkramm commented on .github/scripts/inunin-stall.ps1
> +
Why not solve this with native PowerShell instead of invoking a third-party executable just for getting files in a folder.
```powershell
$files|Select-Object -Property Name
if(-not ($files.name.Contains('rport.conf'))){
  Write-Error "rport.conf not installed"
}
if(-not ($files.name.Contains('rport.exe'))){
  Write-Error "rport.exec not installed"
}
```

2023-02-17 10:51 UTC, thorstenkramm commented on .github/scripts/inunin-stall.ps1
> +	Write-Output "wrong services installed"
`Write-Error` without exit seems more appropriated.
With `$ErrorActionPreference = 'Stop'` the script will exit here.

2023-02-17 11:25 UTC, edoardoc commented on .github/scripts/inunin-stall.ps1
> +
Why: that "third-party executable" is pretty old and stable :D, whereas powershell is microsoft everchanging attempt to take on bash - moreover - I could not find a PS way to list a folder with minimal amount of informations such as
```
~ ls
rport.conf
rport.exe
```

Politics aside your solution looks better and more readable - I will use it.

2023-02-22 13:27 UTC, closed without merging