Issue/dev 2773/api token management improvement
cloudradar-monitoring/rport pull request #921
Opened 2023-02-23 10:15 UTC by edoardoc

https://tracker.rport.io/issue/DEV-2773/api-token-management-improvement

2023-02-23 13:23 UTC, thorstenkramm requested changes

2023-02-23 13:23 UTC, thorstenkramm commented on db/migration/api_token/sql/001_init.up.sql
>  CREATE TABLE api_token (
If the endpoint is plural, the table must use plural too. `api_tokens`.

2023-02-23 13:23 UTC, thorstenkramm commented on db/migration/api_token/sql/001_init.up.sql
> +CREATE UNIQUE INDEX api_token_unique_name
see above

2023-02-23 13:23 UTC, thorstenkramm commented on api-doc/openapi/paths/me_token.yaml
>              prefix:
The API shall return just the token, including the prefix. The prefix is useless and irrelevant for the user.

2023-02-23 13:44 UTC, domenipavec requested changes

2023-02-23 13:44 UTC, domenipavec commented on db/migration/api_token/sql/001_init.up.sql
> +    name TEXT NOT NULL,
This migration won't be run for existing databases. You should create a new migration that adds a column.

2023-02-23 13:44 UTC, domenipavec commented on server/api_handler_login_test.go
> +			if strings.HasPrefix(fmt.Sprintf("%d", tc.wantStatusCode), "2") { // any 2** status code is a success test case
This is a bit weird way to test this, you could just do `tc.wantStatusCode/100 == 2`.

2023-02-23 13:44 UTC, domenipavec commented on server/api_handler_login_test.go
> +					require.Equal(tc.wantErrTitle, tResponse.Errors[0].Title)
You should use `assert.Equal` so the test continues if this is not equal and we can see all failures.
`require` should be used in cases when it makes no sense to continue, like above if json unmarshal fails with errors it makes no sense to do these comparisons.

2023-02-24 07:05 UTC, edoardoc commented on db/migration/api_token/sql/001_init.up.sql
>  CREATE TABLE api_token (
Entities should be named in a singular way - especially database ones and regardless whatever bs one does on the next layer.
I could speak about this for a while, though checking the codebase I understand there is the same mistake in all other tables so I will just follow the convention here.

2023-02-24 07:08 UTC, edoardoc commented on server/api_handler_login_test.go
> +			if strings.HasPrefix(fmt.Sprintf("%d", tc.wantStatusCode), "2") { // any 2** status code is a success test case
oups :)

2023-02-28 16:28 UTC, domenipavec commented on server/api_handler_me.go
> +		r.ExpiresAt = ptr.Time(createdAt.AddDate(1, 0, 0))
Is this a requirement to not have tokens without expiration date?

Can you add a comment so it's clear what is getting added? Like `AddDate(1 /* year */, 0, 0)`

2023-02-28 18:35 UTC, edoardoc commented on server/api_handler_me.go
> +		r.ExpiresAt = ptr.Time(createdAt.AddDate(1, 0, 0))
yes it is a requirement, default for expiry date is 1 year from creation date (if not provided)
I will add a comment

2023-03-01 14:17 UTC, merged