[DEV-2766] client labels
cloudradar-monitoring/rport pull request #929
Opened 2023-02-28 23:26 UTC by KonradKuznicki

https://tracker.rport.io/issue/DEV-2766
expanding client metadata with additional "labels"  key-value attributes, with API filtering and Docs

2023-03-02 18:13 UTC, domenipavec requested changes

2023-03-02 18:13 UTC, domenipavec commented on cmd/rport/cliboilerplate/params_init.go
> +package cliboilerplate
I'm not sure based on what you decided to split this in a separate package? It's not used anywhere else. I would rather you keep it together and just put it in separate files.

2023-03-02 18:13 UTC, domenipavec commented on cmd/rport/main.go
> +	must.Must0f(RootCmd.Execute(), "failed executing RootCmd: %v")
This `must` library makes code harder to read in my opinion. We're all used to error checks and are used to reading the code written that way. This aligns the code differently and I don't really see any benefit in most cases.

If you feel strongly about using this library I think you should bring it up in a team meeting and we can decide as a team if we like it. It shouldn't be a decision made by the 2 of us in this PR.

2023-03-02 18:13 UTC, domenipavec commented on server/clients/cr_test.go
> +				// TODO: kk: figure out how to make it work
I don't like keeping such TODOs in the code, they tend to stay forever. Either make it work, or remove the TODO and create a ticket with the work required.

2023-03-02 18:13 UTC, domenipavec commented on cmd/rport/main.go
> +type ClientAttributesConfigHolder struct {
I'm not sure why this code for reading config file is here in `main.go`. I think it would belong with the rest of parse and validate config code much more naturally.

2023-03-02 18:16 UTC, domenipavec commented
Also, I'm not sure why you made a PR form your fork and not a branch on this repo. But this way doesn't run lint and tests, and I'm not sure how to trigger them.

2023-03-07 14:03 UTC, KonradKuznicki commented on bdd/client_labels/e2e_test.go
> +package simple_client_connects_test
This requirement is only valid for production code packages while this is a helper "test" package that is both valid and recomended

2023-03-07 14:04 UTC, KonradKuznicki commented on cmd/rport/main.go
> +	must.Must0f(RootCmd.Execute(), "failed executing RootCmd: %v")
Agreed, return error and log fatal instead

2023-03-07 14:10 UTC, KonradKuznicki commented on bdd/client_labels/e2e_test.go
> +	ctx                           context.Context
fixed

2023-03-07 16:44 UTC, domenipavec commented on bdd/client_labels/e2e_test.go
> +package simple_client_connects_test
@KonradKuznicki I actually meant it should be `client_labels_test`, so the part before the `_test` suffix matches the folder. I'm fine with the test suffix.

2023-03-08 08:49 UTC, KonradKuznicki commented on bdd/client_labels/e2e_test.go
> +package simple_client_connects_test
Sorry didn't notice this one, fixed

2023-03-08 08:53 UTC, KonradKuznicki commented on share/query/matches_filter.go
> +				clientFieldSliceToMatch = append(clientFieldSliceToMatch, fmt.Sprintf("%v_%v", key, val))
I wanted to show that it's not doing what you expect, 
so it's not any kind of search language and just a string
though on the second thought it's probably better to keep it as ": "

2023-03-09 05:36 UTC, morestatic commented on bdd/client_labels/rport.conf
> +#======================================================================================================================
i agree with @domenipavec here. any reason for keeping the full configs?

2023-03-09 10:55 UTC, morestatic commented on bdd/client_labels/e2e_test.go
> +package client_labels_test
the e2e tests are good to have but are we missing some low level tests? ideally, i wouldn't want to depend on the e2e tests in a code, refactor, test cycle.

2023-03-09 11:06 UTC, morestatic commented on cmd/rport/cliboilerplate/service.go
> +package cliboilerplate
i think you answered this in our call. i'll resolve.

2023-03-10 08:23 UTC, KonradKuznicki commented on cmd/rport/cliboilerplate/params_init.go
> +package cliboilerplate
refactored

2023-03-10 08:23 UTC, KonradKuznicki commented on cmd/rport/main.go
> +type ClientAttributesConfigHolder struct {
refactored

2023-03-10 08:24 UTC, KonradKuznicki commented on cmd/rport/cliboilerplate/service.go
> +package cliboilerplate
As we spoke, the updated is pushed

2023-03-10 08:27 UTC, KonradKuznicki commented on share/query/matches_filter.go
> +
Here is something approximating it 
[server/clients/cr_test.go](https://github.com/cloudradar-monitoring/rport/pull/929/files#diff-bff7567e586f127e60f7390640e0dc6dbedaafd57f3d498ffe9186e448607558R474)

2023-03-10 08:34 UTC, KonradKuznicki commented on share/query/matches_filter.go
> +
I added test you metioned https://github.com/cloudradar-monitoring/rport/pull/929/files#diff-e74abf2df080b5bfa753292d2c18d844e26b3c93960d1a163f64e338bd961f06R89

2023-03-10 08:36 UTC, KonradKuznicki commented on docs/content/advanced/no11-attributes.md
> + - 2-dimensional labels  `"lables": {"country": "Germany", "city": "Cologne", "datacenter": "NetCologne GmbH" }`
longer story unfortunately yes - because it's serialized into string

2023-03-17 17:10 UTC, domenipavec approved these changes

2023-03-20 16:42 UTC, domenipavec commented on go.mod
> +	github.com/KonradKuznicki/must v0.2.0
Is this still used anywhere?

2023-03-21 09:23 UTC, domenipavec approved these changes

2023-03-21 09:24 UTC, merged