quotes in service installation by wix
cloudradar-monitoring/rport pull request #951
Opened 2023-03-14 13:13 UTC by edoardoc

2023-03-14 16:41 UTC, thorstenkramm requested changes

2023-03-14 16:41 UTC, thorstenkramm commented on .github/scripts/msi-publish.ps1
> - -F file=@$upload -F dest_dir="rport/unstable/msi"
see above

2023-03-15 08:56 UTC, edoardoc commented on .github/scripts/msi-publish.ps1
> + -F file=$zip -F dest_dir="rport/unstable/msi"
I did it on the basis of this:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/368717/225255387-454fe3c4-5f4b-420f-a3ce-3d66cbe0aa8c.png">

in this run, 
https://github.com/edoardoc/rport/actions/runs/4414690925/jobs/7736722177

I have made a mistake using transfer.sh which does a PUT with the option --upload-file that does not require the @ 
the @ is needed only if you do a POST with a -F (form)

correcting it in moments...

2023-03-15 09:07 UTC, edoardoc commented on opt/resource/Product.wxs
> +								<ServiceConfig DelayedAutoStart="no" OnInstall="yes" OnReinstall ="yes" />
I did it on the basis of the output of 
```Get-WmiObject win32_service | ?{$_.NAME -like 'rport'} | select * > rport.log```
after installing rport with the:
```& "C:\Program Files\rport\rport.exe" --service install --config 'C:\Program Files\RPort\rport.conf'```

I have attached the two files rport.log and wix.log 
You will see that the only difference is on the AcceptStop property, which I dont believe is very important, but it can be changed...

[wix.log](https://github.com/cloudradar-monitoring/rport/files/10977851/wix.log)
[rport.log](https://github.com/cloudradar-monitoring/rport/files/10977852/rport.log)

2023-03-15 09:10 UTC, edoardoc commented on .github/scripts/msi-publish.ps1
> - -F file=@$upload -F dest_dir="rport/unstable/msi"
fixed

2023-03-16 06:18 UTC, merged